# Generated by Django 5.0.14 on 2026-08-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_number',
            field=models.CharField(blank=True, help_text="Supplier's invoice/bill number", max_length=100, null=True),
        ),
    ]
