# Generated by Django 5.0.14 on 2026-07-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Fenix IT Mall', max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('tagline', models.CharField(default='Smart Inventory • Smart Business', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('currency_code', models.CharField(default='INR', max_length=5)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
